### ISSUE TITLE
Payout amounts bug after first payout

### ISSUE THREAD

**Issue by feruzm** [GolosChain/tolstoy#318] opened 2017-03-14 14:50 UTC
Payout values doesn't show properly after `first_payout` period.

![image](https://s5.postimg.org/hcrbksb5j/Screen_Shot_2017_03_14_at_4_46_59_PM.png)

**EDIT:** After refresh issue is gone, but I leave it open to check caching issue perhaps can add double condition checks

**Comment by serejandmyself** [comment] 2017-03-14 14:53
[![Безымянный.jpg](https://s12.postimg.org/4x148ze1p/image.jpg)](https://postimg.org/image/hbnw9b5jt/)

**Comment by serejandmyself** [comment] 2017-03-14 14:59
Can you make sure again that it isnt a local issue?

**Comment by feruzm** [comment] 2017-03-14 15:02
yes @serejandmyself, I have edited my initial report, right after refresh it resolved itself. And perhaps can added extra conditional checks in code or make to refresh payout amounts when user clicks on details button...

**Comment by serejandmyself** [comment] 2017-03-14 15:04
Yes, that might be a good idea. Next week we will be working on a few related issues. 

Meanwhile, will close this, as the problem is slightly different

**Closed by serejandmyself** 2017-03-14 15:04 UTC
Labels: ?
